# Generated by Django 5.0.2 on 2024-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='host',
            name='first_name',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='host',
            name='last_name',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='host',
            name='middle_name',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
