# Generated by Django 5.0.2 on 2024-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_host_address_host_first_name_host_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
