# Generated by Django 5.0.2 on 2024-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_host_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='phone_number',
        ),
    ]
