# Generated by Django 5.0.2 on 2024-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_host_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
