# Generated by Django 5.0.2 on 2024-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
