# Generated by Django 5.0.2 on 2024-03-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref',
            new_name='reference',
        ),
    ]
